@extends('layouts.website')

@section('title', 'ProntoVia Escolas — Acompanhe a preparação dos seus alunos')
@section('description', 'ProntoVia Escolas: organize turmas, aplique testes e acompanhe resultados, dificuldades por tema e evolução dos candidatos à condução.')

@section('content')
<section class="pv-page-hero pv-school-hero {{ config('prontovia.images.school_hero') ? 'pv-has-background-image' : '' }}" @if(config('prontovia.images.school_hero')) style="--pv-background-image: url('{{ asset(config('prontovia.images.school_hero')) }}')" @endif><div class="container"><div class="row align-items-center gy-5">
    <div class="col-lg-6"><span class="pv-eyebrow"><i class="bi bi-buildings" aria-hidden="true"></i> ProntoVia Escolas</span><h1>Prepare melhor os alunos. Fortaleça a sua escola.</h1><p class="pv-lead">Organize turmas, identifique dificuldades e mostre um acompanhamento mais próximo — uma experiência capaz de gerar confiança, diferenciação e novas recomendações.</p><div class="pv-hero-actions"><a class="pv-btn pv-btn-accent" href="#contacto">Quero fortalecer a minha escola</a><a class="pv-btn pv-btn-secondary" href="#vantagens">Ver vantagens</a></div><p class="pv-brand-promise"><span></span> Mais clareza para ensinar. Mais confiança para escolher.</p></div>
    <div class="col-lg-6"><div class="pv-school-dashboard pv-school-dashboard-large"><div class="pv-dashboard-bar"><span></span><span></span><span></span><strong>Escola · Painel de acompanhamento</strong></div><div class="pv-dashboard-stats"><div><small>Turmas</small><strong>04</strong></div><div><small>Alunos</small><strong>86</strong></div><div><small>Testes</small><strong>12</strong></div></div><div class="pv-dashboard-body"><div class="pv-chart"><span style="height:32%"></span><span style="height:46%"></span><span style="height:55%"></span><span style="height:67%"></span><span style="height:76%"></span><span style="height:84%"></span></div><div class="pv-dashboard-list"><span>Prioridade · reforçar</span><span>Sinais · sólido</span><span>Velocidade · em evolução</span></div></div><small>Dados meramente ilustrativos</small></div></div>
</div></div></section>

<section class="pv-section pv-school-value-section" id="vantagens"><div class="container">
    <div class="row align-items-end gy-4 gx-lg-5"><div class="col-lg-7"><span class="pv-kicker">Valor para a escola</span><h2>Acompanhar o progresso também é uma forma de crescer.</h2></div><div class="col-lg-5"><p class="pv-section-copy">Quando a escola identifica dificuldades cedo e comunica o acompanhamento com clareza, entrega uma experiência mais consistente — algo que alunos e famílias podem reconhecer e recomendar.</p></div></div>
    <div class="pv-school-value-flow">
        <div><span>01</span><h3>Intervenha mais cedo</h3><p>Use resultados por aluno, turma e tema para planear reforços com propósito.</p></div>
        <div><span>02</span><h3>Demonstre acompanhamento</h3><p>Mostre que a preparação não termina na sala: existe continuidade, orientação e evolução.</p></div>
        <div><span>03</span><h3>Diferencie a escola</h3><p>Uma experiência mais organizada pode fortalecer a reputação, a retenção e a recomendação da escola.</p></div>
    </div>
    <div class="pv-school-growth-cta"><p><strong>O ProntoVia não promete matrículas.</strong> Ajuda a construir uma proposta de valor mais clara e uma experiência que pode tornar a escola mais atrativa.</p><a class="pv-btn pv-btn-primary" href="#contacto">Quero conversar sobre a minha escola</a></div>
</div></section>

<section class="pv-section pv-school-principle-section"><div class="container"><div class="pv-principle-grid"><div><span class="pv-principle-number">01</span><h2>A escola acompanha.</h2><p>O painel ajuda a organizar alunos, aplicar avaliações e compreender resultados.</p></div><div><span class="pv-principle-number">02</span><h2>O aluno mantém autonomia.</h2><p>A experiência individual do candidato continua completa e não depende da ligação escolar.</p></div></div><p class="pv-principle-summary"><i class="bi bi-link-45deg"></i> ProntoVia sem escola = produto completo. <strong>ProntoVia + escola = experiência ampliada.</strong></p></div></section>

<section class="pv-section" id="ferramentas"><div class="container"><div class="pv-section-heading text-center mx-auto"><span class="pv-kicker">Ferramentas já disponíveis</span><h2>Da organização da turma à leitura dos resultados.</h2><p>Uma área de trabalho focada no acompanhamento pedagógico.</p></div><div class="row g-4">
    @foreach([['collection','Turmas','Organize candidatos em turmas da sua escola.'],['people','Alunos','Registe e acompanhe os alunos de cada turma.'],['clipboard2-check','Testes','Crie provas manualmente ou por critérios.'],['broadcast-pin','Sessões','Aplique provas por sessão e código de acesso.'],['card-checklist','Resultados','Consulte tentativas, notas e aprovação pedagógica.'],['pie-chart','Análise por tema','Identifique os temas com mais dificuldades.'],['graph-up-arrow','Evolução da turma','Compare o desempenho ao longo das sessões.'],['download','Exportação','Exporte resultados para acompanhamento interno.']] as [$icon,$title,$text])
        <div class="col-sm-6 col-lg-3"><article class="pv-detail-card pv-school-tool"><span class="pv-icon"><i class="bi bi-{{ $icon }}"></i></span><h3>{{ $title }}</h3><p>{{ $text }}</p></article></div>
    @endforeach
</div></div></section>

<section class="pv-section pv-light-section"><div class="container"><div class="row align-items-center gy-5 gx-lg-5"><div class="col-lg-6"><span class="pv-kicker">Resultados acionáveis</span><h2>Veja a turma sem perder de vista cada aluno.</h2><p class="pv-section-copy">Acompanhe médias, temas mais falhados, evolução por sessão e indicadores de prontidão para orientar reforços e novas avaliações.</p><ul class="pv-check-list"><li><i class="bi bi-check2"></i> Resumo por turma</li><li><i class="bi bi-check2"></i> Detalhe por aluno e tentativa</li><li><i class="bi bi-check2"></i> Breakdown de desempenho por tema</li><li><i class="bi bi-check2"></i> Histórico de sessões</li></ul></div><div class="col-lg-6"><div class="pv-analytics-card"><div class="pv-analytics-head"><div><small>Turma B</small><strong>Temas a reforçar</strong></div><span>Últimas sessões</span></div>@foreach([['Prioridade',62],['Manobras',68],['Velocidade',77]] as [$topic,$value])<div class="pv-analytics-row"><span>{{ $topic }}</span><div class="pv-progress-track"><span style="width:{{ $value }}%"></span></div><strong>{{ $value }}%</strong></div>@endforeach<div class="pv-analytics-note"><i class="bi bi-lightbulb"></i> Planeie uma sessão de reforço sobre prioridade.</div></div></div></div></div></section>

<section class="pv-section"><div class="container"><div class="row align-items-center gy-5 gx-lg-5"><div class="col-lg-5"><div class="pv-future-link"><i class="bi bi-person-bounding-box"></i><span class="one">Conta do aluno</span><span class="line"></span><i class="bi bi-buildings"></i><span class="two">Painel da escola</span></div></div><div class="col-lg-7"><span class="pv-kicker">Integração opcional</span><h2>Uma ligação que amplia, sem criar dependência.</h2><p class="pv-section-copy">Hoje, a área escolar e a conta individual funcionam separadamente. A ligação opcional entre ambas está prevista como evolução: permitirá à escola acompanhar, enquanto o aluno conserva a sua conta e o seu percurso.</p><p class="pv-status-note"><i class="bi bi-info-circle"></i> Esta integração ainda não está disponível e não é apresentada como funcionalidade atual.</p></div></div></div></section>

<section class="pv-section pv-instructors"><div class="container"><div class="pv-instructors-inner"><span class="pv-icon"><i class="bi bi-person-workspace"></i></span><div><span class="pv-kicker">Instrutores</span><h2>Permissões específicas estão previstas.</h2><p>O painel atual permite utilizadores associados à escola, mas ainda não possui um perfil autónomo de instrutor nem atribuição de instrutores a turmas. Esta evolução poderá trazer responsabilidades e acessos mais granulares.</p></div></div></div></section>

<section class="pv-section" id="contacto"><div class="container"><div class="pv-contact-card"><div><span class="pv-kicker pv-kicker-light">Para escolas</span><h2>Vamos transformar acompanhamento em valor para a escola?</h2><p>Conte-nos como prepara os alunos hoje. Vamos identificar onde o ProntoVia pode melhorar a gestão, a experiência dos candidatos e a diferenciação da sua escola.</p></div><div class="pv-contact-action">
    @if(config('prontovia.school_url'))<a class="pv-btn pv-btn-accent" href="{{ config('prontovia.school_url') }}">Falar com a equipa</a>@elseif(config('prontovia.support_email'))<a class="pv-btn pv-btn-accent" href="mailto:{{ config('prontovia.support_email') }}?subject=ProntoVia%20Escolas">Contactar por email</a>@else<span><i class="bi bi-envelope"></i><strong>Canal comercial em preparação</strong><small>O contacto será disponibilizado aqui assim que estiver configurado.</small></span>@endif
</div></div></div></section>
@endsection
