@extends('layouts.admin')
@section('title','Operações escolares')
@section('page-title','Operações escolares')
@section('page-subtitle','Instrutores, vínculos e tarefas num único espaço de operação da escola.')
@section('content')
<div class="school-operations-page">
    <x-admin.page-header title="{{ $school->name }}" description="Gira quem ensina, quem está vinculado e o trabalho que precisa de ser feito." />
    @if($schools->count() > 1)<form method="GET" class="data-toolbar"><label class="field"><span>Escola</span><select name="school_id" onchange="this.form.submit()">@foreach($schools as $option)<option value="{{ $option->id }}" @selected($option->id === $school->id)>{{ $option->name }}</option>@endforeach</select></label></form>@endif
    <div class="operations-grid">
        <section class="admin-surface"><div class="surface-heading"><div><h2>Instrutores</h2><p>{{ $instructors->count() }} instrutor(es) e respetivas turmas.</p></div><x-admin.button data-dialog-open="create-instructor"><i class="bi bi-person-plus" aria-hidden="true"></i>Novo instrutor</x-admin.button></div>
            <x-admin.table caption="Instrutores"><x-slot:head><tr><th>Instrutor</th><th>Turmas atribuídas</th><th>Estado</th><th>Ações</th></tr></x-slot:head>@forelse($instructors as $instructor)<tr><td><strong>{{ $instructor->user->name }}</strong><small>{{ $instructor->user->email }}</small></td><td>{{ $instructor->classrooms->pluck('name')->join(', ') ?: 'Nenhuma' }}</td><td><x-admin.state :type="$instructor->is_active ? 'approved' : 'neutral'">{{ $instructor->is_active ? 'Ativo' : 'Inativo' }}</x-admin.state></td><td><x-admin.row-actions label="Ações do instrutor"><button type="button" role="menuitem" data-dialog-open="edit-instructor-{{ $instructor->id }}"><i class="bi bi-pencil" aria-hidden="true"></i>Editar</button><button type="button" role="menuitem" data-dialog-open="attach-instructor-{{ $instructor->id }}"><i class="bi bi-link-45deg" aria-hidden="true"></i>Atribuir turma</button></x-admin.row-actions></td></tr>@empty<x-admin.empty-state table :colspan="4" icon="person-workspace" title="Ainda não existem instrutores" description="Crie o primeiro perfil de instrutor para distribuir responsabilidades." />@endforelse</x-admin.table>
        </section>
        <section class="admin-surface"><div class="surface-heading"><div><h2>Vínculos escolares</h2><p>Convites e estados dos candidatos da escola.</p></div><x-admin.button data-dialog-open="create-membership"><i class="bi bi-person-plus" aria-hidden="true"></i>Convidar candidato</x-admin.button></div>
            <x-admin.table caption="Vínculos escolares"><x-slot:head><tr><th>Candidato</th><th>Turma</th><th>Estado</th><th>Ações</th></tr></x-slot:head>@forelse($memberships as $membership)<tr><td><strong>{{ $membership->mobileUser?->name ?: 'Sem nome' }}</strong><small>{{ $membership->mobileUser?->email ?: $membership->mobileUser?->phone }}</small></td><td>{{ $membership->classroom?->name ?: '—' }}</td><td><x-admin.state type="{{ $membership->status === 'active' ? 'approved' : ($membership->status === 'invited' ? 'review' : 'neutral') }}">{{ ucfirst($membership->status) }}</x-admin.state></td><td>@if(in_array($membership->status,['active','suspended']))<form method="POST" action="{{ route('admin.school-memberships.status',$membership) }}" class="inline-form">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $membership->status === 'active' ? 'suspended' : 'completed' }}"><button class="btn btn-small" type="submit">{{ $membership->status === 'active' ? 'Suspender' : 'Concluir' }}</button></form>@endif</td></tr>@empty<x-admin.empty-state table :colspan="4" icon="people" title="Sem vínculos" description="Convide um candidato para começar." />@endforelse</x-admin.table></section>
        <section class="admin-surface operations-wide"><div class="surface-heading"><div><h2>Tarefas</h2><p>Treino, leitura, simulados, testes e revisão para turmas ou candidatos.</p></div><x-admin.button data-dialog-open="create-assignment"><i class="bi bi-plus-lg" aria-hidden="true"></i>Nova tarefa</x-admin.button></div>
            <x-admin.table caption="Tarefas escolares"><x-slot:head><tr><th>Tarefa</th><th>Destino</th><th>Estado</th><th>Progresso</th><th>Ações</th></tr></x-slot:head>@forelse($assignments as $assignment)<tr><td><strong>{{ $assignment->title }}</strong><small>{{ ucfirst($assignment->type) }}</small></td><td>{{ $assignment->classroom?->name ?: ($assignment->mobileUser?->name ?: '—') }}</td><td><x-admin.state type="{{ $assignment->status === 'published' ? 'approved' : ($assignment->status === 'draft' ? 'review' : 'neutral') }}">{{ ucfirst($assignment->status) }}</x-admin.state></td><td>{{ $assignment->progress_count }} destinatário(s)</td><td>@if($assignment->status === 'draft')<form method="POST" action="{{ route('admin.assignments.status',$assignment) }}" class="inline-form">@csrf @method('PATCH')<input type="hidden" name="action" value="publish"><button class="btn btn-small" type="submit">Publicar</button></form>@elseif($assignment->status === 'published')<form method="POST" action="{{ route('admin.assignments.status',$assignment) }}" class="inline-form">@csrf @method('PATCH')<input type="hidden" name="action" value="close"><button class="btn btn-small" type="submit">Encerrar</button></form>@endif</td></tr>@empty<x-admin.empty-state table :colspan="5" icon="clipboard-check" title="Ainda não existem tarefas" description="Crie a primeira tarefa para uma turma ou candidato." />@endforelse</x-admin.table></section>
    </div>
</div>
<x-admin.dialog id="create-instructor" title="Novo instrutor" description="Crie uma conta com acesso limitado às turmas atribuídas."><form id="create-instructor-form" method="POST" action="{{ route('admin.instructors.store') }}" class="modal-form-grid">@csrf<input type="hidden" name="school_id" value="{{ $school->id }}"><x-admin.field name="name" label="Nome" required /><x-admin.field name="email" label="Email" type="email" required /><x-admin.field name="password" label="Palavra-passe" type="password" minlength="8" required /><x-admin.field name="license_number" label="Número profissional" /><x-admin.field name="bio" label="Nota" as="textarea" rows="2" class="modal-form-full" /></form><x-slot:footer><x-admin.button variant="secondary" data-dialog-close>Cancelar</x-admin.button><x-admin.button type="submit" form="create-instructor-form">Criar instrutor</x-admin.button></x-slot:footer></x-admin.dialog>
@foreach($instructors as $instructor)<x-admin.dialog id="edit-instructor-{{ $instructor->id }}" title="Editar instrutor" description="Atualize dados e estado da conta."><form id="edit-instructor-form-{{ $instructor->id }}" method="POST" action="{{ route('admin.instructors.update',$instructor) }}" class="modal-form-grid">@csrf @method('PUT')<x-admin.field name="name" label="Nome" value="{{ $instructor->user->name }}" required /><x-admin.field name="email" label="Email" type="email" value="{{ $instructor->user->email }}" required /><x-admin.field name="password" label="Nova palavra-passe" type="password" minlength="8" /><x-admin.field name="license_number" label="Número profissional" value="{{ $instructor->license_number }}" /><x-admin.field name="bio" label="Nota" as="textarea" rows="2" class="modal-form-full">{{ $instructor->bio }}</x-admin.field><label class="pv-checkbox modal-form-full"><input type="checkbox" name="is_active" value="1" @checked($instructor->is_active)> Instrutor ativo</label></form><x-slot:footer><x-admin.button variant="secondary" data-dialog-close>Cancelar</x-admin.button><x-admin.button type="submit" form="edit-instructor-form-{{ $instructor->id }}">Guardar</x-admin.button></x-slot:footer></x-admin.dialog><x-admin.dialog id="attach-instructor-{{ $instructor->id }}" title="Atribuir turma" description="O instrutor só verá dados das turmas atribuídas."><form id="attach-instructor-form-{{ $instructor->id }}" method="POST" action="{{ route('admin.instructors.attach',$instructor) }}">@csrf<x-admin.field as="select" name="classroom_id" label="Turma" required><option value="">Selecione</option>@foreach($classrooms as $classroom)<option value="{{ $classroom->id }}">{{ $classroom->name }}</option>@endforeach</x-admin.field></form><x-slot:footer><x-admin.button variant="secondary" data-dialog-close>Cancelar</x-admin.button><x-admin.button type="submit" form="attach-instructor-form-{{ $instructor->id }}">Atribuir</x-admin.button></x-slot:footer></x-admin.dialog>@endforeach
<x-admin.dialog id="create-membership" title="Convidar candidato" description="O candidato terá de aceitar o convite na aplicação."><form id="create-membership-form" method="POST" action="{{ route('admin.school-memberships.invite') }}" class="modal-form-grid">@csrf<input type="hidden" name="school_id" value="{{ $school->id }}"><x-admin.field as="select" name="mobile_user_id" label="Candidato" required><option value="">Selecione</option>@foreach($mobileUsers as $candidate)<option value="{{ $candidate->id }}">{{ $candidate->name ?: $candidate->phone }} — {{ $candidate->email }}</option>@endforeach</x-admin.field><x-admin.field as="select" name="classroom_id" label="Turma"><option value="">Sem turma por agora</option>@foreach($classrooms as $classroom)<option value="{{ $classroom->id }}">{{ $classroom->name }}</option>@endforeach</x-admin.field></form><x-slot:footer><x-admin.button variant="secondary" data-dialog-close>Cancelar</x-admin.button><x-admin.button type="submit" form="create-membership-form">Enviar convite</x-admin.button></x-slot:footer></x-admin.dialog>
<x-admin.dialog id="create-assignment" title="Nova tarefa" description="Escolha uma turma ou um candidato, nunca os dois."><form id="create-assignment-form" method="POST" action="{{ route('admin.assignments.store') }}" class="modal-form-grid">@csrf<input type="hidden" name="school_id" value="{{ $school->id }}"><x-admin.field name="title" label="Título" required class="modal-form-full" /><x-admin.field as="select" name="type" label="Tipo" required><option value="training">Treino</option><option value="reading">Leitura</option><option value="simulation">Simulado</option><option value="test">Teste</option><option value="revision">Revisão</option></x-admin.field><x-admin.field as="select" name="classroom_id" label="Turma"><option value="">— ou candidato —</option>@foreach($classrooms as $classroom)<option value="{{ $classroom->id }}">{{ $classroom->name }}</option>@endforeach</x-admin.field><x-admin.field as="select" name="mobile_user_id" label="Candidato"><option value="">Selecione se não for turma</option>@foreach($mobileUsers as $candidate)<option value="{{ $candidate->id }}">{{ $candidate->name ?: $candidate->phone }}</option>@endforeach</x-admin.field><x-admin.field name="due_at" label="Prazo" type="datetime-local" /><x-admin.field name="instructions" label="Instruções" as="textarea" rows="3" class="modal-form-full" /></form><x-slot:footer><x-admin.button variant="secondary" data-dialog-close>Cancelar</x-admin.button><x-admin.button type="submit" form="create-assignment-form">Criar rascunho</x-admin.button></x-slot:footer></x-admin.dialog>
@endsection
