@extends('layouts.admin')
@section('title','Perguntas')
@section('page-title','Perguntas')
@section('page-subtitle','Crie, organize e acompanhe o conteúdo de avaliação.')
@section('content')
<div class="toolbar"><div><h2>Banco de perguntas</h2><p>{{ $questions->total() }} registos encontrados</p></div><a class="btn" href="{{ route('admin.questions.create') }}">＋ Nova pergunta</a></div>
<form class="filters" method="GET"><input name="q" value="{{ request('q') }}" placeholder="Enunciado ou identificador"><select name="topic"><option value="">Todos os temas</option>@foreach($topics as $topic)<option value="{{ $topic->id }}" @selected(request('topic') == $topic->id)>{{ $topic->name }}</option>@endforeach</select><select name="type"><option value="">Todos os tipos</option><option value="teorico" @selected(request('type')==='teorico')>Teórico</option><option value="pratico" @selected(request('type')==='pratico')>Prático</option></select><select name="category"><option value="">Todas as cartas</option>@foreach($categories as $category)<option value="{{ $category->slug }}" @selected(request('category')===$category->slug)>{{ $category->name }}</option>@endforeach</select><select name="status"><option value="">Todos os estados</option>@foreach(['draft'=>'Rascunho','review'=>'Em revisão','approved'=>'Aprovada','rejected'=>'Rejeitada'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button class="btn light">Filtrar</button></form>
<section class="card table-card"><table class="data-table"><thead><tr><th>ID</th><th>Pergunta</th><th>Tema / tipo</th><th>Categoria</th><th>Autor</th><th>Estado</th><th>Ações</th></tr></thead><tbody>
@forelse($questions as $question)<tr><td><small>{{ $question->external_id }}</small></td><td><strong>{{ str($question->statement)->limit(72) }}</strong><br><small>{{ count($question->options) }} opções · Artigo {{ $question->article_ref ?: '—' }}</small></td><td>{{ $question->topic->name }}<br><small>{{ ucfirst($question->type) }}</small></td><td><small>{{ implode(', ', $question->categories) }}</small></td><td>{{ $question->author?->name ?? 'Sistema' }}<br><small>{{ $question->school?->name }}</small></td><td><span class="status {{ $question->status }}">{{ ['draft'=>'Rascunho','review'=>'Em revisão','approved'=>'Aprovada','rejected'=>'Rejeitada'][$question->status] }}</span></td><td class="actions"><a class="btn light small" href="{{ route('admin.questions.edit',$question) }}">Editar</a><form method="POST" action="{{ route('admin.questions.destroy',$question) }}" onsubmit="return confirm('Remover esta pergunta?')">@csrf @method('DELETE')<button class="btn danger small">Remover</button></form></td></tr>@empty<tr><td colspan="7" class="empty">Ainda não existem perguntas.</td></tr>@endforelse
</tbody></table></section><div class="pagination">{{ $questions->links() }}</div>
@endsection
