@extends('layouts.admin')
@section('title', 'Glossário')
@section('page-title', 'Glossário de termos')
@section('page-subtitle', 'Definições curtas e pesquisáveis para apoiar o estudo e as explicações das perguntas.')
@section('content')
<div class="glossary-page">
    <x-admin.page-header id="glossary-page-title" title="Glossário de termos" description="Organize conceitos que costumam gerar dúvidas e ligue-os à base legal." :count="$total" count-label="termos">
        @if(auth()->user()->isAdmin())<details class="pv-create-menu"><summary class="btn"><i class="bi bi-plus-lg" aria-hidden="true"></i>Novo termo</summary><form class="pv-create-form glossary-create-form" method="POST" action="{{ route('admin.glossary.store') }}">@csrf<x-admin.field name="term" label="Termo" required placeholder="Ex.: berma" /><x-admin.field name="article_ref" label="Artigo de referência" type="number" min="1" /><x-admin.field name="definition" label="Definição" as="textarea" rows="4" required /><x-admin.field name="sort_order" label="Ordem" type="number" min="0" value="0" /><label class="pv-checkbox"><input type="checkbox" name="is_active" value="1" checked> Ativo</label><label class="pv-checkbox"><input type="checkbox" name="is_locked" value="1"> Plano completo</label><x-admin.button type="submit">Adicionar termo</x-admin.button></form></details>@endif
    </x-admin.page-header>
    <form method="get" class="data-toolbar glossary-filters" aria-label="Pesquisar glossário"><label class="pv-table-search"><i class="bi bi-search" aria-hidden="true"></i><input name="q" value="{{ request('q') }}" placeholder="Pesquisar termo ou definição" aria-label="Termo ou definição"></label><x-admin.button type="submit" variant="secondary"><i class="bi bi-search" aria-hidden="true"></i>Pesquisar</x-admin.button>@if(request('q'))<x-admin.button variant="secondary" :href="route('admin.glossary.index')">Limpar</x-admin.button>@endif</form>
    <x-admin.table class="glossary-table" labelledby="glossary-page-title" caption="Glossário de termos"><x-slot:head><tr><th scope="col">Termo</th><th scope="col">Definição</th><th scope="col">Base legal</th><th scope="col">Acesso</th><th scope="col" class="pv-actions-column">Ações</th></tr></x-slot:head>
        @forelse($terms as $term)<tr><td class="glossary-term"><strong>{{ $term->term }}</strong></td><td class="glossary-definition"><span>{{ str($term->definition)->limit(180) }}</span></td><td>{{ $term->article_ref ? 'Art. '.$term->article_ref : '—' }}</td><td><x-admin.state :type="$term->is_active ? 'approved' : 'neutral'">{{ $term->is_active ? 'Ativo' : 'Inativo' }}</x-admin.state><small class="glossary-plan">{{ $term->is_locked ? 'Plano completo' : 'Gratuito' }}</small></td><td class="actions"><x-admin.row-actions :view-href="route('admin.glossary.show', $term)" label="Ações do termo">@if(auth()->user()->isAdmin())<form method="POST" action="{{ route('admin.glossary.destroy', $term) }}" onsubmit="return confirm('Remover este termo?')" role="menuitem">@csrf @method('DELETE')<button type="submit" class="is-danger"><i class="bi bi-trash3" aria-hidden="true"></i>Remover</button></form>@endif</x-admin.row-actions></td></tr>@empty<x-admin.empty-state table :colspan="5" icon="book" title="Glossário vazio" description="Comece pelos termos que mais confundem os alunos." />@endforelse
    </x-admin.table><x-admin.pagination :paginator="$terms" />
</div>
@endsection
