@extends('layouts.admin')
@section('title','Desbloqueios')
@section('page-title','Desbloqueios e pagamentos')
@section('page-subtitle','Registo manual dos pagamentos M-Pesa/e-Mola. O acesso só é concedido quando o desbloqueio está associado a uma conta.')
@section('content')
@if($semConta)
<p class="alert warning">{{ $semConta }} pagamento(s) ativo(s) ainda sem conta associada. Esses alunos continuam no plano gratuito até confirmarem o código no app — ou até associar aqui a conta, se já se registaram.</p>
@endif
<section class="split-grid"><form class="card inline-form" method="POST" action="{{ route('admin.unlocks.store') }}">@csrf<div class="field"><label>Telefone</label><input name="phone" placeholder="+258 84..." required></div><div class="field"><label>Plano</label><input name="plan" value="completo" required></div><div class="field"><label>Pagamento</label><select name="payment_method"><option value="mpesa">M-Pesa</option><option value="emola">e-Mola</option><option value="manual">Manual</option><option value="outro">Outro</option></select></div><div class="field"><label>Referência</label><input name="payment_reference"></div><div class="field"><label>Data</label><input type="datetime-local" name="unlocked_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></div><div class="field"><label>Validade opcional</label><input type="datetime-local" name="expires_at"></div><div class="field full"><label>Notas</label><textarea name="notes"></textarea></div><div class="field full"><div class="checks"><label><input type="checkbox" name="is_active" value="1" checked> Ativo</label></div></div><div class="form-actions full"><button class="btn">Registar desbloqueio</button></div></form>
<div><form class="filters"><input name="q" value="{{ request('q') }}" placeholder="Telefone ou referência"><button class="btn light">Pesquisar</button></form><section class="card table-card"><table class="data-table"><thead><tr><th>Telefone</th><th>Plano</th><th>Pagamento</th><th>Data</th><th>Conta</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($unlocks as $unlock)<tr><td><strong>{{ $unlock->phone }}</strong></td><td>{{ $unlock->plan }}</td><td>{{ strtoupper($unlock->payment_method ?: '—') }}<br><small>{{ $unlock->payment_reference }}</small></td><td>{{ $unlock->unlocked_at->format('d/m/Y') }}</td><td>@if($unlock->mobileUser)<span class="status approved">{{ $unlock->mobileUser->email }}</span>@else<span class="status review">Sem conta</span>@endif</td><td><span class="status {{ $unlock->is_active ? 'active' : 'inactive' }}">{{ $unlock->is_active ? 'Ativo' : 'Inativo' }}</span></td><td class="actions">@unless($unlock->mobileUser)<form method="POST" action="{{ route('admin.unlocks.bind',$unlock) }}">@csrf @method('PATCH')<button class="btn light small">Associar conta</button></form>@endunless<form method="POST" action="{{ route('admin.unlocks.destroy',$unlock) }}">@csrf @method('DELETE')<button class="btn danger small">Remover</button></form></td></tr>@empty<tr><td class="empty" colspan="7">Nenhum número desbloqueado.</td></tr>@endforelse</tbody></table></section><div class="pagination">{{ $unlocks->links() }}</div></div></section>
@endsection
