@extends('layouts.admin')
@section('title','Publicação')
@section('page-title','Publicação de pacotes')
@section('page-subtitle','Gere versões do conteúdo aprovado distribuído pela API.')
@section('content')
<section class="metric-grid" style="margin-bottom:16px"><article class="card metric-card"><span class="metric-icon green">✓</span><div><span>Perguntas aprovadas</span><strong>{{ $approvedCount }}</strong></div></article><article class="card metric-card"><span class="metric-icon blue">▤</span><div><span>Provas públicas publicadas</span><strong>{{ $publishedExamsCount }}</strong></div></article>@foreach($byTopic->take(2) as $topic)<article class="card metric-card"><span class="metric-icon blue">?</span><div><span>{{ $topic->name }}</span><strong>{{ $topic->questions_count }}</strong></div></article>@endforeach</section>
<form class="card" style="padding:20px;margin-bottom:16px" method="POST" action="{{ route('admin.publications.publish') }}">@csrf<div class="toolbar"><div><h2>Publicar novo pacote</h2><p>Inclui perguntas aprovadas e uma cópia offline das provas públicas já publicadas.</p></div><button class="btn">Publicar agora</button></div><div class="field"><label>Notas da versão</label><textarea name="notes" placeholder="Resumo opcional das alterações"></textarea></div></form>
<section class="card table-card"><table class="data-table"><thead><tr><th>Versão</th><th>Publicação</th><th>Perguntas</th><th>Estado</th><th>Ações</th></tr></thead><tbody>@forelse($packages as $package)<tr><td><strong>{{ $package->version }}</strong><br><small>{{ $package->notes }}</small></td><td>{{ $package->published_at?->format('d/m/Y H:i') }}<br><small>{{ $package->publisher?->name }}</small></td><td>{{ $package->question_count }}</td><td><span class="status {{ $package->status==='published' ? 'approved' : 'draft' }}">{{ $package->status==='published' ? 'Publicado' : 'Arquivado' }}</span></td><td class="actions"><a class="btn light small" href="{{ route('admin.publications.download',$package) }}">JSON</a>@if($package->status!=='published')<form method="POST" action="{{ route('admin.publications.restore',$package) }}">@csrf @method('PATCH')<button class="btn warning small">Repor</button></form>@endif</td></tr>@empty<tr><td class="empty" colspan="5">Nenhum pacote publicado.</td></tr>@endforelse</tbody></table></section><div class="pagination">{{ $packages->links() }}</div>
@endsection
