@extends('layouts.admin')
@section('title','Publicação')
@section('page-title','Publicação de pacotes')
@section('page-subtitle','Gere versões do conteúdo aprovado distribuído pela API.')
@section('content')
<div class="publications-page">
    <x-admin.page-header id="publications-page-title" title="Publicação de pacotes" description="Publique uma versão rastreável do conteúdo aprovado para o aplicativo." :count="$packages->total()" count-label="versões">
        <x-admin.button data-dialog-open="create-publication"><i class="bi bi-upload" aria-hidden="true"></i>Publicar novo pacote</x-admin.button>
    </x-admin.page-header>
    <section class="publication-readiness" aria-label="Prontidão para publicação"><div><span>Perguntas aprovadas</span><strong>{{ $approvedCount }}</strong><small>ativas e prontas para distribuição</small></div><div><span>Provas públicas</span><strong>{{ $publishedExamsCount }}</strong><small>incluídas no pacote offline</small></div><div class="publication-topics"><span>Conteúdo por tema</span><div>@foreach($byTopic->take(3) as $topic)<small><b>{{ $topic->questions_count }}</b> {{ $topic->name }}</small>@endforeach</div></div></section>
    <section class="publication-history" aria-labelledby="publications-history-title"><header class="publication-section-head"><div><h3 id="publications-history-title">Histórico de versões</h3><p>Uma versão publicada fica disponível para download autenticado; as anteriores podem ser restauradas.</p></div></header>
        <x-admin.table class="publications-table" labelledby="publications-history-title" caption="Histórico de pacotes publicados"><x-slot:head><tr><th scope="col">Versão</th><th scope="col">Publicação</th><th scope="col">Conteúdo</th><th scope="col">Estado</th><th scope="col" class="pv-actions-column">Ações</th></tr></x-slot:head>
            @forelse($packages as $package)<tr><td class="publication-version"><strong>{{ $package->version }}</strong><small>{{ $package->notes ?: 'Sem notas da versão' }}</small></td><td class="publication-date"><strong>{{ $package->published_at?->format('d/m/Y H:i') ?: '—' }}</strong><small>{{ $package->publisher?->name ?: 'Sistema' }}</small></td><td><strong>{{ $package->question_count }}</strong><small class="publication-meta">perguntas aprovadas</small></td><td><x-admin.state :type="$package->status === 'published' ? 'approved' : 'neutral'">{{ $package->status === 'published' ? 'Publicado' : 'Arquivado' }}</x-admin.state></td><td class="actions"><x-admin.row-actions :view-href="route('admin.publications.show',$package)" label="Ações da versão"><a href="{{ route('admin.publications.download',$package) }}" role="menuitem"><i class="bi bi-download" aria-hidden="true"></i>Baixar JSON</a>@if($package->status !== 'published')<form method="POST" action="{{ route('admin.publications.restore',$package) }}" role="menuitem">@csrf @method('PATCH')<button type="submit"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i>Restaurar versão</button></form>@endif</x-admin.row-actions></td></tr>@empty<x-admin.empty-state table :colspan="5" icon="cloud-upload" title="Nenhum pacote publicado" description="Publique a primeira versão para distribuir o conteúdo aprovado." />@endforelse
        </x-admin.table><x-admin.pagination :paginator="$packages" />
    </section>
</div>
<x-admin.dialog id="create-publication" title="Publicar novo pacote" description="O pacote inclui perguntas aprovadas e uma cópia offline das provas públicas já publicadas."><form id="create-publication-form" method="POST" action="{{ route('admin.publications.publish') }}">@csrf<x-admin.field name="notes" label="Notas da versão" as="textarea" rows="4" placeholder="Resumo opcional das alterações" /></form><x-slot:footer><x-admin.button variant="secondary" data-dialog-close>Cancelar</x-admin.button><x-admin.button type="submit" form="create-publication-form"><i class="bi bi-upload" aria-hidden="true"></i>Publicar agora</x-admin.button></x-slot:footer></x-admin.dialog>
@endsection
