@extends('layouts.admin')
@section('title','Categorias')
@section('page-title','Categorias de carta')
@section('page-subtitle','Etiquetas utilizadas para filtrar perguntas e provas.')
@section('content')
<div class="taxonomy-page">
<x-admin.page-header id="license-categories-title" title="Categorias de carta" description="Mantenha as categorias disponíveis para perguntas, provas e filtros." :count="$categories->count()" count-label="categorias"><x-admin.button data-dialog-open="create-license-category"><i class="bi bi-plus-lg" aria-hidden="true"></i>Nova categoria</x-admin.button></x-admin.page-header>
<x-admin.table class="license-categories-table" labelledby="license-categories-title" caption="Categorias de carta"><x-slot:head><tr><th scope="col">Categoria</th><th scope="col">Ordem</th><th scope="col">Estado</th><th scope="col" class="pv-actions-column">Ações</th></tr></x-slot:head>
@forelse($categories as $category)
<tr><td class="taxonomy-main"><strong>{{ $category->name }}</strong><small>{{ $category->description ?: 'Sem descrição' }}</small></td><td>{{ $category->sort_order }}</td><td><x-admin.state :type="$category->is_active ? 'approved' : 'neutral'">{{ $category->is_active ? 'Ativa' : 'Inativa' }}</x-admin.state></td><td class="actions"><x-admin.row-actions label="Ações da categoria"><button type="button" data-dialog-open="edit-license-category-{{ $category->id }}"><i class="bi bi-pencil" aria-hidden="true"></i>Editar</button><form method="POST" action="{{ route('admin.categories.destroy',$category) }}" role="menuitem">@csrf @method('DELETE')<button type="submit" class="is-danger"><i class="bi bi-trash3" aria-hidden="true"></i>Remover</button></form></x-admin.row-actions></td></tr>
@empty
<x-admin.empty-state table :colspan="4" icon="tags" title="Ainda não existem categorias" description="Crie a primeira categoria para começar a classificar perguntas." />
@endforelse
</x-admin.table>
</div>
<x-admin.dialog id="create-license-category" title="Nova categoria de carta" description="A categoria ficará disponível para perguntas e provas."><form id="create-license-category-form" method="POST" action="{{ route('admin.categories.store') }}" class="modal-form-grid">@csrf<x-admin.field name="name" label="Nome" required /><x-admin.field name="slug" label="Identificador" placeholder="ligeiro" required /><x-admin.field name="description" label="Descrição" as="textarea" rows="3" class="modal-form-full" /><x-admin.field name="sort_order" label="Ordem" type="number" min="0" value="0" required /><label class="pv-checkbox"><input type="checkbox" name="is_active" value="1" checked> Categoria ativa</label></form><x-slot:footer><x-admin.button variant="secondary" data-dialog-close>Cancelar</x-admin.button><x-admin.button type="submit" form="create-license-category-form">Guardar categoria</x-admin.button></x-slot:footer></x-admin.dialog>
@foreach($categories as $category)<x-admin.dialog id="edit-license-category-{{ $category->id }}" title="Editar categoria" description="Atualize o nome, a descrição ou o estado."><form id="edit-license-category-form-{{ $category->id }}" method="POST" action="{{ route('admin.categories.update',$category) }}" class="modal-form-grid">@csrf @method('PUT')<x-admin.field name="name" label="Nome" value="{{ $category->name }}" required /><x-admin.field name="slug" label="Identificador" value="{{ $category->slug }}" required /><x-admin.field name="description" label="Descrição" as="textarea" rows="3" class="modal-form-full">{{ $category->description }}</x-admin.field><x-admin.field name="sort_order" label="Ordem" type="number" min="0" value="{{ $category->sort_order }}" required /><label class="pv-checkbox"><input type="checkbox" name="is_active" value="1" @checked($category->is_active)> Categoria ativa</label></form><x-slot:footer><x-admin.button variant="secondary" data-dialog-close>Cancelar</x-admin.button><x-admin.button type="submit" form="edit-license-category-form-{{ $category->id }}">Guardar alterações</x-admin.button></x-slot:footer></x-admin.dialog>@endforeach
@endsection
