@extends('layouts.admin')
@section('title','Provas')
@section('page-title','Provas')
@section('page-subtitle','Provas públicas com publicação controlada e provas privadas das escolas.')
@section('content')
<div class="toolbar"><div><h2>Provas organizadas</h2><p>{{ $exams->total() }} provas · cada prova contém perguntas selecionadas</p></div><a class="btn" href="{{ route('admin.exams.create') }}">＋ Nova prova</a></div>
<section class="card table-card"><table class="data-table"><thead><tr><th>Prova</th><th>Acesso</th><th>Publicação</th><th>Categorias</th><th>Perguntas</th><th>Aprovação</th><th>Ações</th></tr></thead><tbody>
@forelse($exams as $exam)<tr><td><strong>{{ $exam->name }}</strong><br><small>{{ $exam->creator?->name }}</small></td><td><span class="status {{ $exam->is_public ? 'active' : 'inactive' }}">{{ $exam->is_public ? 'Pública · app' : 'Privada · escola' }}</span><br><small>{{ $exam->school?->name }}</small></td><td>@if($exam->is_public)<span class="status {{ ['published'=>'approved','archived'=>'inactive','draft'=>'review'][$exam->publication_status] ?? 'draft' }}">{{ ['published'=>'Publicada','archived'=>'Arquivada','draft'=>'Rascunho'][$exam->publication_status] ?? ucfirst($exam->publication_status) }}</span><br><span class="status {{ $exam->is_locked ? 'review' : 'approved' }}">{{ $exam->is_locked ? 'Plano completo' : 'Gratuita' }}</span>@else<span class="status inactive">Não aplicável</span>@endif</td><td>{{ implode(', ', $exam->license_categories ?: [$exam->license_category]) }}</td><td>{{ $exam->questions_count }}</td><td>{{ $exam->pass_score }}/{{ $exam->question_count }}</td><td class="actions"><a class="btn light small" href="{{ route('admin.exams.show',$exam) }}">Ver</a>@if(auth()->user()->isAdmin() && $exam->is_public && $exam->publication_status !== 'published')<form method="POST" action="{{ route('admin.exams.publish',$exam) }}">@csrf @method('PATCH')<button class="btn small">Publicar no app</button></form>@elseif(auth()->user()->isAdmin() && $exam->is_public)<form method="POST" action="{{ route('admin.exams.archive',$exam) }}">@csrf @method('PATCH')<button class="btn warning small">Arquivar</button></form>@endif
@if(auth()->user()->isAdmin() && $exam->is_public)<form method="POST" action="{{ route('admin.exams.plan',$exam) }}">@csrf @method('PATCH')<button class="btn light small">{{ $exam->is_locked ? 'Abrir ao plano gratuito' : 'Marcar plano completo' }}</button></form>@endif<form method="POST" action="{{ route('admin.exams.destroy',$exam) }}" onsubmit="return confirm('Remover esta prova?')">@csrf @method('DELETE')<button class="btn danger small">Remover</button></form></td></tr>
@empty<tr><td class="empty" colspan="7">Ainda não existem provas.</td></tr>@endforelse
</tbody></table></section><div class="pagination">{{ $exams->links() }}</div>
@endsection
