@extends('layouts.admin')
@section('title',$mobileUser->name)
@section('page-title',$mobileUser->name)
@section('page-subtitle','Perfil e aprendizagem no aplicativo')
@section('content')
<div class="toolbar"><div><a href="{{ route('admin.mobile-users.index') }}">← Utilizadores do aplicativo</a><p>{{ $mobileUser->email }} · {{ $mobileUser->phone }} · Categoria {{ ucfirst($mobileUser->license_category) }}</p></div><div class="actions"><a class="btn light" href="{{ route('admin.unlocks.index', ['q' => $mobileUser->phone]) }}">Gerir plano</a><form method="POST" action="{{ route('admin.mobile-users.status', $mobileUser) }}">@csrf @method('PATCH')<button class="btn {{ $mobileUser->is_active ? 'danger' : '' }}">{{ $mobileUser->is_active ? 'Desativar conta' : 'Ativar conta' }}</button></form></div></div>
<section class="metric-grid"><article class="card metric-card"><span class="metric-icon blue">▤</span><div><span>Testes resolvidos</span><strong>{{ $exams->count() }}</strong></div></article><article class="card metric-card"><span class="metric-icon green">%</span><div><span>Média nos testes</span><strong>{{ $examAverage }}%</strong></div></article><article class="card metric-card"><span class="metric-icon yellow">?</span><div><span>Respostas registadas</span><strong>{{ $answers->count() }}</strong></div></article><article class="card metric-card"><span class="metric-icon green">✓</span><div><span>Conteúdos lidos</span><strong>{{ $readContents->count() }}</strong></div></article></section>
<section class="dashboard-grid"><article class="card panel"><h3>Conta e plano</h3><dl class="detail-grid"><div class="detail-field"><dt>Estado</dt><dd><span class="status {{ $mobileUser->is_active ? 'active' : 'inactive' }}">{{ $mobileUser->is_active ? 'Ativa' : 'Inativa' }}</span></dd></div><div class="detail-field"><dt>Plano</dt><dd>{{ $unlock?->plan ?? 'Grátis' }}</dd></div><div class="detail-field"><dt>Validade</dt><dd>{{ $unlock?->expires_at?->format('d/m/Y H:i') ?? ($unlock ? 'Sem expiração' : '—') }}</dd></div><div class="detail-field"><dt>Último acesso</dt><dd>{{ $lastSeenAt ? \Illuminate\Support\Carbon::parse($lastSeenAt)->format('d/m/Y H:i') : 'Nunca' }}</dd></div><div class="detail-field"><dt>Desde</dt><dd>{{ $mobileUser->created_at->format('d/m/Y') }}</dd></div><div class="detail-field"><dt>Precisão geral</dt><dd>{{ $answerAccuracy }}%</dd></div></dl></article>
<article class="card panel"><h3>Fraquezas por tema</h3><div class="activity">@forelse($weaknesses as $weakness)<div class="activity-item"><span class="activity-icon">{{ $weakness['accuracy'] }}%</span><div><strong>{{ str($weakness['topic'])->replace('_',' ')->title() }}</strong><small>{{ $weakness['errors'] }} erros em {{ $weakness['total'] }} respostas</small></div><span class="status {{ $weakness['accuracy'] >= 72 ? 'approved' : 'rejected' }}">{{ $weakness['accuracy'] >= 72 ? 'Bom' : 'Reforçar' }}</span></div>@empty<div class="empty">Ainda não existem respostas para calcular fraquezas.</div>@endforelse</div></article></section>
<section class="card panel" style="margin-top:14px"><h3>Testes realizados</h3><div class="table-card"><table class="data-table"><thead><tr><th>Teste</th><th>Resultado</th><th>Nota</th><th>Tempo</th><th>Data</th></tr></thead><tbody>@forelse($exams as $exam)<tr><td>Teste {{ $exam->number }}</td><td><strong>{{ $exam->correct_answers }}/{{ $exam->total }}</strong></td><td>{{ round($exam->correct_answers / max(1,$exam->total) * 100,1) }}% · {{ round($exam->correct_answers / max(1,$exam->total) * 20,1) }} valores</td><td>{{ gmdate('i:s',$exam->duration_seconds) }}</td><td>{{ $exam->completed_at->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="5" class="empty">Nenhum teste realizado.</td></tr>@endforelse</tbody></table></div></section>
<section class="dashboard-grid"><article class="card panel"><h3>Conteúdos consultados</h3><div class="activity">@forelse($readContents as $content)@php($number = (int) str($content->content_key)->afterLast(':')->value())<div class="activity-item"><span class="activity-icon">§</span><div><strong>{{ $articles->get($number)?->title ?? str($content->content_key)->replace(':',' · ')->title() }}</strong><small>{{ $articles->has($number) ? 'Artigo '.$number.' · ' : '' }}{{ $content->updated_at->format('d/m/Y H:i') }}</small></div></div>@empty<div class="empty">Nenhum conteúdo consultado.</div>@endforelse</div></article><article class="card panel"><h3>Revisões agendadas</h3><div class="activity">@forelse($revisions as $revision)<div class="activity-item"><span class="activity-icon">◷</span><div><strong>{{ str($revision->topic)->replace('_',' ')->title() }}</strong><small>Pergunta {{ $revision->question_external_id }} · {{ $revision->scheduled_for->format('d/m/Y H:i') }}</small></div><span class="status {{ $revision->scheduled_for->isPast() ? 'review' : 'active' }}">{{ $revision->scheduled_for->isPast() ? 'Pendente' : 'Agendada' }}</span></div>@empty<div class="empty">Nenhuma revisão agendada.</div>@endforelse</div></article></section>
@endsection
