@extends('layouts.admin')
@section('title','Sessões')
@section('page-title','Aplicar prova')
@section('page-subtitle','Gere um link, inicie a sessão e acompanhe as submissões.')
@section('content')
<x-admin.page-header id="session-list-title" title="Sessões de prova" description="Gere links de acesso e acompanhe a participação das turmas." :count="$sessions->total()" count-label="sessões">
    <details class="pv-create-menu"><summary class="btn"><i class="bi bi-plus-lg" aria-hidden="true"></i>Nova sessão</summary>
        <form class="pv-create-form session-create-form" method="POST" action="{{ route('admin.sessions.store') }}">@csrf
            <x-admin.field as="select" name="exam_id" label="Prova privada" required><option value="">Escolher prova privada</option>@foreach($exams as $exam)<option value="{{ $exam->id }}" data-school="{{ $exam->school_id }}" @selected(old('exam_id') == $exam->id)>{{ $exam->name }} — {{ $exam->school?->name }}</option>@endforeach</x-admin.field>
            <x-admin.field as="select" name="classroom_id" label="Turma" required><option value="">Primeiro escolha a prova</option>@foreach($classrooms as $classroom)<option value="{{ $classroom->id }}" data-school="{{ $classroom->school_id }}" @selected(old('classroom_id') == $classroom->id)>{{ $classroom->name }} — {{ $classroom->school?->name }}</option>@endforeach</x-admin.field>
            <x-admin.button type="submit"><i class="bi bi-link-45deg" aria-hidden="true"></i>Gerar sessão e link</x-admin.button>
        </form>
    </details>
</x-admin.page-header>

<x-admin.table class="sessions-table" labelledby="session-list-title" caption="Sessões de prova">
<x-slot:head><tr><th scope="col">Código e link</th><th scope="col">Prova</th><th scope="col">Turma</th><th scope="col">Submissões</th><th scope="col">Estado</th><th scope="col" class="pv-actions-column">Ações</th></tr></x-slot:head>
@forelse($sessions as $session)
@php($entryUrl = route('student-exam.entry',$session->code))
<tr><td class="session-code"><strong>{{ $session->code }}</strong><a href="{{ $entryUrl }}" target="_blank" rel="noopener">Abrir link <i class="bi bi-box-arrow-up-right" aria-hidden="true"></i></a><button type="button" class="session-copy" data-copy-link="{{ $entryUrl }}"><i class="bi bi-copy" aria-hidden="true"></i>Copiar link</button></td><td class="session-main"><strong>{{ $session->exam->name }}</strong><small>{{ $session->exam->school?->name ?? '—' }}</small></td><td>{{ $session->classroom->name }}</td><td><strong>{{ $session->attempts_count }}</strong><small class="session-meta">de {{ $session->classroom->students()->count() }} alunos</small></td><td><x-admin.state :type="$session->status === 'in_progress' ? 'review' : ($session->status === 'finished' ? 'approved' : 'draft')">{{ ['scheduled'=>'Agendada','in_progress'=>'Em curso','finished'=>'Terminada'][$session->status] }}</x-admin.state></td><td class="actions"><x-admin.row-actions :view-href="route('admin.sessions.show',$session)" label="Ações da sessão">@if($session->status === 'scheduled')<form method="POST" action="{{ route('admin.sessions.update',$session) }}" role="menuitem">@csrf @method('PUT')<input type="hidden" name="status" value="in_progress"><button type="submit"><i class="bi bi-play-circle" aria-hidden="true"></i>Iniciar sessão</button></form>@elseif($session->status === 'in_progress')<form method="POST" action="{{ route('admin.sessions.update',$session) }}" role="menuitem">@csrf @method('PUT')<input type="hidden" name="status" value="finished"><button type="submit"><i class="bi bi-stop-circle" aria-hidden="true"></i>Terminar sessão</button></form>@endif<button type="button" role="menuitem" class="is-danger" data-dialog-open="delete-session-{{ $session->id }}"><i class="bi bi-trash3" aria-hidden="true"></i>Remover</button></x-admin.row-actions></td></tr>
@empty
<x-admin.empty-state table :colspan="6" icon="broadcast" title="Nenhuma sessão criada" description="Crie uma sessão para gerar um link de acesso à prova." />
@endforelse
</x-admin.table>
<x-admin.pagination :paginator="$sessions" />

@foreach($sessions as $session)<x-admin.dialog id="delete-session-{{ $session->id }}" title="Remover sessão?" description="Os resultados já submetidos devem ser preservados quando necessário."><p>Vai remover a sessão <strong>{{ $session->code }}</strong>.</p><x-slot:footer><x-admin.button variant="secondary" data-dialog-close>Cancelar</x-admin.button><form method="POST" action="{{ route('admin.sessions.destroy',$session) }}">@csrf @method('DELETE')<x-admin.button variant="danger" type="submit" loading-label="A remover…">Remover sessão</x-admin.button></form></x-slot:footer></x-admin.dialog>@endforeach
<script>document.querySelectorAll('[data-copy-link]').forEach(function(button){button.addEventListener('click',function(){navigator.clipboard.writeText(button.dataset.copyLink).then(function(){var original=button.innerHTML;button.innerHTML='<i class="bi bi-check2" aria-hidden="true"></i>Copiado';window.setTimeout(function(){button.innerHTML=original},1800)}).catch(function(){window.prompt('Copie o link da sessão:',button.dataset.copyLink)})})});var sessionExam=document.getElementById('field-exam_id'),sessionClassroom=document.getElementById('field-classroom_id'),sessionOptions=sessionClassroom?[].slice.call(sessionClassroom.querySelectorAll('option[data-school]')):[];function filterSessionClassrooms(){if(!sessionExam||!sessionClassroom)return;var selected=sessionExam.options[sessionExam.selectedIndex],school=selected?selected.dataset.school:null,current=sessionClassroom.value;sessionOptions.forEach(function(option){option.hidden=!school||option.dataset.school!==school;option.disabled=option.hidden});if(!sessionOptions.some(function(option){return !option.hidden&&option.value===current}))sessionClassroom.value='';sessionClassroom.options[0].textContent=school?'Escolher turma da mesma escola':'Primeiro escolha a prova'}sessionExam?.addEventListener('change',filterSessionClassrooms);filterSessionClassrooms();</script>
@endsection
