@extends('layouts.admin')
@section('title','Sessões')
@section('page-title','Aplicar prova')
@section('page-subtitle','Gere um link, inicie a sessão e acompanhe as submissões.')
@section('content')
<form class="card" id="session-form" style="display:flex;flex-wrap:wrap;gap:10px;margin-bottom:16px;padding:18px" method="POST" action="{{ route('admin.sessions.store') }}">@csrf<select name="exam_id" id="session-exam" required><option value="">Escolher prova privada</option>@foreach($exams as $exam)<option value="{{ $exam->id }}" data-school="{{ $exam->school_id }}" @selected(old('exam_id') == $exam->id)>{{ $exam->name }} — {{ $exam->school?->name }}</option>@endforeach</select><select name="classroom_id" id="session-classroom" required><option value="">Primeiro escolha a prova</option>@foreach($classrooms as $classroom)<option value="{{ $classroom->id }}" data-school="{{ $classroom->school_id }}" @selected(old('classroom_id') == $classroom->id)>{{ $classroom->name }} — {{ $classroom->school?->name }}</option>@endforeach</select><button class="btn">Gerar sessão e link</button></form>
<section class="card table-card"><table class="data-table"><thead><tr><th>Código e link</th><th>Prova</th><th>Turma</th><th>Submissões</th><th>Estado</th><th>Ações</th></tr></thead><tbody>
@forelse($sessions as $session)<tr><td><strong style="font-size:17px;letter-spacing:.12em">{{ $session->code }}</strong><br><a href="{{ route('student-exam.entry',$session->code) }}" target="_blank"><small>{{ route('student-exam.entry',$session->code) }}</small></a><br><button class="btn light small" type="button" onclick="navigator.clipboard.writeText('{{ route('student-exam.entry',$session->code) }}');this.textContent='Link copiado'">Copiar link</button></td><td>{{ $session->exam->name }}<br><small>{{ $session->exam->school?->name }}</small></td><td>{{ $session->classroom->name }}</td><td>{{ $session->attempts_count }}/{{ $session->classroom->students()->count() }}</td><td><span class="status {{ $session->status==='in_progress' ? 'review' : ($session->status==='finished' ? 'approved' : 'draft') }}">{{ ['scheduled'=>'Agendada','in_progress'=>'Em curso','finished'=>'Terminada'][$session->status] }}</span></td><td class="actions"><a class="btn light small" href="{{ route('admin.sessions.show',$session) }}">Ver</a>@if($session->status==='scheduled')<form method="POST" action="{{ route('admin.sessions.update',$session) }}">@csrf @method('PUT')<input type="hidden" name="status" value="in_progress"><button class="btn small">Iniciar</button></form>@elseif($session->status==='in_progress')<form method="POST" action="{{ route('admin.sessions.update',$session) }}">@csrf @method('PUT')<input type="hidden" name="status" value="finished"><button class="btn warning small">Terminar</button></form>@endif<form method="POST" action="{{ route('admin.sessions.destroy',$session) }}" onsubmit="return confirm('Remover esta sessão?')">@csrf @method('DELETE')<button class="btn danger small">Remover</button></form></td></tr>
@empty<tr><td class="empty" colspan="6">Nenhuma sessão criada.</td></tr>@endforelse
</tbody></table></section><div class="pagination">{{ $sessions->links() }}</div>
<script>
(function(){var exam=document.getElementById('session-exam'),classroom=document.getElementById('session-classroom'),options=[].slice.call(classroom.querySelectorAll('option[data-school]'));function filterClassrooms(){var selected=exam.options[exam.selectedIndex],school=selected?selected.dataset.school:null,current=classroom.value;options.forEach(function(option){option.hidden=!school||option.dataset.school!==school;option.disabled=option.hidden});if(!options.some(function(option){return !option.hidden&&option.value===current}))classroom.value='';classroom.options[0].textContent=school?'Escolher turma da mesma escola':'Primeiro escolha a prova'}exam.addEventListener('change',filterClassrooms);filterClassrooms()})();
</script>
@endsection
